### ISSUE TITLE
We were unable to connect you to the realtime system

### ISSUE THREAD

**Issue by dyhack** [xwiki-contrib/netflux-websocket-webjar#1]
DockerImage:xwiki:13.10.0-mysql-tomcat
I use this image build xwiki,only install Realtime WYSIWYG Editor version 13.10
but it don't work
![image](https://user-images.githubusercontent.com/22422580/145794431-c013eb82-e4e8-41e6-8a55-acd8545e8471.png)

**Comment by mflorea** [comment]
@dyhack this is not the right place to report issues about the real-time WYSIWYG editor in XWiki. Please use https://jira.xwiki.org/issues/?jql=project%20%3D%20XWIKI%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20Realtime . Make sure you specify detailed steps to reproduce. Also make sure you read https://extensions.xwiki.org/xwiki/bin/view/Extension/Realtime%20WYSIWYG%20Editor/ .

**Comment by dyhack** [comment]
thanks

**Comment by dyhack** [comment]
I see this problem has solve in https://jira.xwiki.org/browse/XWIKI-19074      13.10.rc-1
This mean it will solve in xwiki:13.10.0?
but i get the issue in 13.10.0

**Comment by mflorea** [comment]
@dyhack this was the fix applied in 13.10RC1 https://github.com/xwiki/xwiki-platform/commit/df0fc4dcfd5fea35958353c50ca550bb140523b7  and yes, it should be present in 13.10 final version. Look for the ``context.xml`` file corresponding to the XWiki webapp and see if the ``org.apache.tomcat.websocket.server.WsSci`` filter is still active.
